[package]
name = "proven-mvcc"
version.workspace = true
edition.workspace = true

[dependencies]
fjall.workspace = true
proven-common.workspace = true
tempfile.workspace = true

[dev-dependencies]
serde.workspace = true
