[package]
name = "proven-snapshot-memory"
version.workspace = true
edition.workspace = true

[dependencies]
proven-snapshot.workspace = true
serde.workspace = true
sha2.workspace = true
tracing.workspace = true
