[package]
name = "proven-coordinator"
version.workspace = true
edition.workspace = true

[dependencies]
parking_lot = { workspace = true }
proven-engine = { path = "../engine" }
proven-hlc = { workspace = true }
proven-kv = { path = "../kv" }
proven-queue = { path = "../queue" }
proven-sql = { path = "../sql" }
proven-stream = { path = "../stream" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
