[package]
name = "proven-resource"
version = "0.1.0"
edition = "2021"

[dependencies]
ciborium = "0.2"
proven-hlc = { path = "../hlc" }
proven-stream = { path = "../stream" }
rust_decimal = { version = "1.33", features = ["serde-with-str"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
zstd = "0.13"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
tokio-test = "0.4"