[package]
name = "proven-resource-client"
version.workspace = true
edition.workspace = true

[dependencies]
proven-coordinator.workspace = true
proven-resource.workspace = true
rust_decimal.workspace = true
serde_json.workspace = true
thiserror.workspace = true